### ISSUE TITLE
Fix fetch samples

### ISSUE THREAD

**Issue by brauliodiez** [Lemoncode/promises-ts-samples#10]
Fetch samples are broken, issue: es6-promise package plus tsd.

Remove this package from the project.

Add support for core-js (package plus type definitions)

Reference sample:

https://github.com/Lemoncode/react-by-sample/blob/master/12%20TableHttp/package.json

Assigned to @borjamaza

**Comment by atobajas** [comment]
Sorry i am working in migration to Typescript 2.0

**Comment by brauliodiez** [comment]
Great then, go ahead follow the indications, in case you need more help or support @borjamaza can jump on it.

My fault not to create the issue and assign it. Sorry about that.
